### ISSUE TITLE
touch instructions

### ISSUE THREAD

**Issue by wroxall** [MaartenWL/rage#4]
hi
is there a youtube page or setup manual for your App?

**Comment by MaartenWL** [comment]
Hi

no i'm not a video guy at al, sorry. Do you have any specific questions i can help with?

**Comment by wroxall** [comment]
Hi
A comprehensive set of instructions would be nice.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MaartenWL** [comment]
New version Has a webbased support/manuaal page. Easy fit me to  improviseren it over time.
