### ISSUE TITLE
connections

### ISSUE THREAD

**Issue by stevesyber** [MaartenWL/rage#7]
Hi Maarten. Me again. So I have tried every know way to get the midi notes from the daw playing into the Virus and I just cant seem to get it to work. 

From my understanding of what you were saying on the forum the UM-ONE controls the editing of the virus(which it does) and the Bluetooth midi from the controller sends the clock and midi notes to the ipad touch for virus app and then goes to the Virus via the UM-ONE? 

is this correct? if not how do you play notes on the virus rather than just hitting the audit button?

I can play the audit note from the ipad and virus and record it in ableton via the Bluetooth midi and audio but it just doesn't seem to go the other way. 

I have a rack mounted virus so therefore need that midi note to be played back via the ipad.

as before any help would be appreciated.

thanks

Steve

**Comment by MaartenWL** [comment]
Hi Steve,

Thanks for buying Touch for Virus! Let's see if we can make it work for you!
I'm not sure what I was saying in any forum, but i use it as follows:

1) Controller keyboard sends notes to iPad using bluetooth.
2) On the iPad: I use the Cubasis to send the incomming MIDI through to the USB to MIDI interface which is connected to the Virus. (I'm sure other apps can do this as well, doesn't need to be Cubasis)
3) In Touch for Virus I also let is send all data to that same USB to MIDI interface.

Two questions: 
1) I'm not sure if my way will do for you, but for me it works. Can you give it a try
2) Would a MIDI through function in the app help you in any way?

P.S.  But the way, a big update is comming with a larger onscreen keyboard, and more.

**Comment by stevesyber** [comment]
Thanks for getting back to me Maarten,

I will give it a try. I have cubasis but not really sure how to set it all up but will give it a try and get back to you. I just feel like I am missing one part of the puzzle that is right in front of me.

With a midi through would you be able to select the Bluetooth device to receive and send the notes to the virus? Is so that would definitely help. 

Look forward to getting this up and running and also to the new update. 

I hope access is paying attention to your app as they should be very interested in what you are doing. It’s a very good app and I will definitely use it once I get this connection sorted.

Cheers

Steve

**Comment by stevesyber** [comment]
Hi Maarten

So I found I already had 2 midi routing apps on my iPad that allowed me to route from Bluetooth to the usb interface. So I can play the virus from the controller and control the virus from my iPad. The downside is it really doesn’t play nice with the Bluetooth as you said in your notes. So errors happen as soon as I use both and I can’t sync with the virus, see any presents or see any of the settings

Is this something you have looked into for the update of will this still be an issue?

Thanks

Steve

**Comment by MaartenWL** [comment]
Hi!  I'm Using Audiokit inside my app for dealing with the MIDI because that part is really for coding experts, which i'm not. In the new version which is available now, i've been able to upgrade Audiokit from version 4.5 to 4.8. This could make a difference in support for bluetooth. However, Their midi support is in general pretty good, so if they can't get it working there must be a reason. 
I have written down the request for MIDI through  function though.
